include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    constant_identifier_names: ignore
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore

formatter:
  page_width: 120
