include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    avoid_types_on_closure_parameters: ignore
    constant_identifier_names: ignore
    directives_ordering: ignore
    lines_longer_than_80_chars: ignore

formatter:
  page_width: 80 # default
  trailing_commas: preserve
