targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false # default: false
          checked: false # default: false
          constructor: "" # default: ""
          create_factory: true # default: true
          create_to_json: true # default: true
          disallow_unrecognized_keys: false # default: false
          explicit_to_json: true # default: false
          field_rename: none # default: "none"
          generic_argument_factories: false # default: false
          ignore_unannotated: false # default: false
          include_if_null: false # default: true
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
