// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'payment_request.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PaymentRequest _$PaymentRequestFromJson(Map<String, dynamic> json) =>
    PaymentRequest(
      storeId: json['storeId'] as String,
      paymentId: json['paymentId'] as String,
      orderName: json['orderName'] as String,
      totalAmount: (json['totalAmount'] as num).toInt(),
      currency: $enumDecode(_$CurrencyEnumMap, json['currency']),
      payMethod: $enumDecode(_$PaymentPayMethodEnumMap, json['payMethod']),
      appScheme: json['appScheme'] as String,
      pg: $enumDecodeNullable(_$PGCompanyEnumMap, json['pg']),
      channelKey: json['channelKey'] as String?,
      channelGroupId: json['channelGroupId'] as String?,
      taxFreeAmount: (json['taxFreeAmount'] as num?)?.toInt(),
      vatAmount: (json['vatAmount'] as num?)?.toInt(),
      customer: json['customer'] == null
          ? null
          : Customer.fromJson(json['customer'] as Map<String, dynamic>),
      windowType: json['windowType'] == null
          ? null
          : WindowTypes.fromJson(json['windowType'] as Map<String, dynamic>),
      redirectUrl: json['redirectUrl'] as String?,
      forceRedirect: json['forceRedirect'] as bool?,
      noticeUrls: (json['noticeUrls'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      confirmUrl: json['confirmUrl'] as String?,
      isEscrow: json['isEscrow'] as bool?,
      products: (json['products'] as List<dynamic>?)
          ?.map((e) => ProductDetail.fromJson(e as Map<String, dynamic>))
          .toList(),
      locale: $enumDecodeNullable(_$PaymentLocaleEnumMap, json['locale']),
      customData: (json['customData'] as Map<String, dynamic>?)?.map(
        (k, e) => MapEntry(k, e as String),
      ),
      isCulturalExpense: json['isCulturalExpense'] as bool?,
      bypass: json['bypass'] == null
          ? null
          : PaymentBypass.fromJson(json['bypass'] as Map<String, dynamic>),
      country: $enumDecodeNullable(_$CountryEnumMap, json['country']),
      productType: $enumDecodeNullable(
        _$ProductTypeEnumMap,
        json['productType'],
      ),
      expiredTime: json['expiredTime'] as String?,
      cashReceiptTradeOption: $enumDecodeNullable(
        _$CashReceiptTradeOptionEnumMap,
        json['cashReceiptTradeOption'],
      ),
      offerPeriod: json['offerPeriod'] == null
          ? null
          : OfferPeriod.fromJson(json['offerPeriod'] as Map<String, dynamic>),
      storeDetails: json['storeDetails'] == null
          ? null
          : StoreDetails.fromJson(json['storeDetails'] as Map<String, dynamic>),
      shippingAddress: json['shippingAddress'] == null
          ? null
          : Address.fromJson(json['shippingAddress'] as Map<String, dynamic>),
      promotionId: json['promotionId'] as String?,
      popup: json['popup'] == null
          ? null
          : Popup.fromJson(json['popup'] as Map<String, dynamic>),
      iframe: json['iframe'] == null
          ? null
          : Iframe.fromJson(json['iframe'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$PaymentRequestToJson(PaymentRequest instance) =>
    <String, dynamic>{
      'storeId': instance.storeId,
      'paymentId': instance.paymentId,
      'orderName': instance.orderName,
      'totalAmount': instance.totalAmount,
      'currency': _$CurrencyEnumMap[instance.currency],
      'payMethod': _$PaymentPayMethodEnumMap[instance.payMethod],
      'channelKey': ?instance.channelKey,
      'channelGroupId': ?instance.channelGroupId,
      'taxFreeAmount': ?instance.taxFreeAmount,
      'vatAmount': ?instance.vatAmount,
      'customer': ?instance.customer?.toJson(),
      'windowType': ?instance.windowType?.toJson(),
      'redirectUrl': ?instance.redirectUrl,
      'forceRedirect': ?instance.forceRedirect,
      'noticeUrls': ?instance.noticeUrls,
      'confirmUrl': ?instance.confirmUrl,
      'appScheme': instance.appScheme,
      'isEscrow': ?instance.isEscrow,
      'products': ?instance.products?.map((e) => e.toJson()).toList(),
      'isCulturalExpense': ?instance.isCulturalExpense,
      'locale': ?_$PaymentLocaleEnumMap[instance.locale],
      'customData': ?instance.customData,
      'expiredTime': ?instance.expiredTime,
      'bypass': ?instance.bypass?.toJson(),
      'country': ?_$CountryEnumMap[instance.country],
      'productType': ?_$ProductTypeEnumMap[instance.productType],
      'cashReceiptTradeOption':
          ?_$CashReceiptTradeOptionEnumMap[instance.cashReceiptTradeOption],
      'offerPeriod': ?instance.offerPeriod?.toJson(),
      'storeDetails': ?instance.storeDetails?.toJson(),
      'shippingAddress': ?instance.shippingAddress?.toJson(),
      'promotionId': ?instance.promotionId,
      'popup': ?instance.popup?.toJson(),
      'iframe': ?instance.iframe?.toJson(),
    };

const Map<Currency, String> _$CurrencyEnumMap = {
  Currency.KRW: 'KRW',
  Currency.USD: 'USD',
  Currency.EUR: 'EUR',
  Currency.JPY: 'JPY',
  Currency.CNY: 'CNY',
  Currency.VND: 'VND',
  Currency.THB: 'THB',
  Currency.SGD: 'SGD',
  Currency.AUD: 'AUD',
  Currency.HKD: 'HKD',
  Currency.AED: 'AED',
  Currency.AFN: 'AFN',
  Currency.ALL: 'ALL',
  Currency.AMD: 'AMD',
  Currency.ANG: 'ANG',
  Currency.AOA: 'AOA',
  Currency.ARS: 'ARS',
  Currency.AWG: 'AWG',
  Currency.AZN: 'AZN',
  Currency.BAM: 'BAM',
  Currency.BBD: 'BBD',
  Currency.BDT: 'BDT',
  Currency.BGN: 'BGN',
  Currency.BHD: 'BHD',
  Currency.BIF: 'BIF',
  Currency.BMD: 'BMD',
  Currency.BND: 'BND',
  Currency.BOB: 'BOB',
  Currency.BOV: 'BOV',
  Currency.BRL: 'BRL',
  Currency.BSD: 'BSD',
  Currency.BTN: 'BTN',
  Currency.BWP: 'BWP',
  Currency.BYN: 'BYN',
  Currency.BZD: 'BZD',
  Currency.CAD: 'CAD',
  Currency.CDF: 'CDF',
  Currency.CHE: 'CHE',
  Currency.CHF: 'CHF',
  Currency.CHW: 'CHW',
  Currency.CLF: 'CLF',
  Currency.CLP: 'CLP',
  Currency.COP: 'COP',
  Currency.COU: 'COU',
  Currency.CRC: 'CRC',
  Currency.CUC: 'CUC',
  Currency.CUP: 'CUP',
  Currency.CVE: 'CVE',
  Currency.CZK: 'CZK',
  Currency.DJF: 'DJF',
  Currency.DKK: 'DKK',
  Currency.DOP: 'DOP',
  Currency.DZD: 'DZD',
  Currency.EGP: 'EGP',
  Currency.ERN: 'ERN',
  Currency.ETB: 'ETB',
  Currency.FJD: 'FJD',
  Currency.FKP: 'FKP',
  Currency.GBP: 'GBP',
  Currency.GEL: 'GEL',
  Currency.GHS: 'GHS',
  Currency.GIP: 'GIP',
  Currency.GMD: 'GMD',
  Currency.GNF: 'GNF',
  Currency.GTQ: 'GTQ',
  Currency.GYD: 'GYD',
  Currency.HNL: 'HNL',
  Currency.HRK: 'HRK',
  Currency.HTG: 'HTG',
  Currency.HUF: 'HUF',
  Currency.IDR: 'IDR',
  Currency.ILS: 'ILS',
  Currency.INR: 'INR',
  Currency.IQD: 'IQD',
  Currency.IRR: 'IRR',
  Currency.ISK: 'ISK',
  Currency.JMD: 'JMD',
  Currency.JOD: 'JOD',
  Currency.KES: 'KES',
  Currency.KGS: 'KGS',
  Currency.KHR: 'KHR',
  Currency.KMF: 'KMF',
  Currency.KPW: 'KPW',
  Currency.KWD: 'KWD',
  Currency.KYD: 'KYD',
  Currency.KZT: 'KZT',
  Currency.LAK: 'LAK',
  Currency.LBP: 'LBP',
  Currency.LKR: 'LKR',
  Currency.LRD: 'LRD',
  Currency.LSL: 'LSL',
  Currency.LYD: 'LYD',
  Currency.MAD: 'MAD',
  Currency.MDL: 'MDL',
  Currency.MGA: 'MGA',
  Currency.MKD: 'MKD',
  Currency.MMK: 'MMK',
  Currency.MNT: 'MNT',
  Currency.MOP: 'MOP',
  Currency.MRU: 'MRU',
  Currency.MUR: 'MUR',
  Currency.MVR: 'MVR',
  Currency.MWK: 'MWK',
  Currency.MXN: 'MXN',
  Currency.MXV: 'MXV',
  Currency.MZN: 'MZN',
  Currency.NAD: 'NAD',
  Currency.NGN: 'NGN',
  Currency.NIO: 'NIO',
  Currency.NOK: 'NOK',
  Currency.NPR: 'NPR',
  Currency.NZD: 'NZD',
  Currency.OMR: 'OMR',
  Currency.PAB: 'PAB',
  Currency.PEN: 'PEN',
  Currency.PGK: 'PGK',
  Currency.PHP: 'PHP',
  Currency.PKR: 'PKR',
  Currency.PLN: 'PLN',
  Currency.PYG: 'PYG',
  Currency.QAR: 'QAR',
  Currency.RON: 'RON',
  Currency.RSD: 'RSD',
  Currency.RUB: 'RUB',
  Currency.RWF: 'RWF',
  Currency.SAR: 'SAR',
  Currency.SBD: 'SBD',
  Currency.SCR: 'SCR',
  Currency.SDG: 'SDG',
  Currency.SEK: 'SEK',
  Currency.SHP: 'SHP',
  Currency.SLE: 'SLE',
  Currency.SLL: 'SLL',
  Currency.SOS: 'SOS',
  Currency.SRD: 'SRD',
  Currency.SSP: 'SSP',
  Currency.STN: 'STN',
  Currency.SVC: 'SVC',
  Currency.SYP: 'SYP',
  Currency.SZL: 'SZL',
  Currency.TJS: 'TJS',
  Currency.TMT: 'TMT',
  Currency.TND: 'TND',
  Currency.TOP: 'TOP',
  Currency.TRY: 'TRY',
  Currency.TTD: 'TTD',
  Currency.TWD: 'TWD',
  Currency.TZS: 'TZS',
  Currency.UAH: 'UAH',
  Currency.UGX: 'UGX',
  Currency.USN: 'USN',
  Currency.UYI: 'UYI',
  Currency.UYU: 'UYU',
  Currency.UYW: 'UYW',
  Currency.UZS: 'UZS',
  Currency.VED: 'VED',
  Currency.VES: 'VES',
  Currency.VUV: 'VUV',
  Currency.WST: 'WST',
  Currency.XAF: 'XAF',
  Currency.XAG: 'XAG',
  Currency.XAU: 'XAU',
  Currency.XBA: 'XBA',
  Currency.XBB: 'XBB',
  Currency.XBC: 'XBC',
  Currency.XBD: 'XBD',
  Currency.XCD: 'XCD',
  Currency.XDR: 'XDR',
  Currency.XOF: 'XOF',
  Currency.XPD: 'XPD',
  Currency.XPF: 'XPF',
  Currency.XPT: 'XPT',
  Currency.XSU: 'XSU',
  Currency.XTS: 'XTS',
  Currency.XUA: 'XUA',
  Currency.XXX: 'XXX',
  Currency.YER: 'YER',
  Currency.ZAR: 'ZAR',
  Currency.ZMW: 'ZMW',
  Currency.ZWL: 'ZWL',
};

const Map<PaymentPayMethod, String> _$PaymentPayMethodEnumMap = {
  PaymentPayMethod.card: 'CARD',
  PaymentPayMethod.virtualAccount: 'VIRTUAL_ACCOUNT',
  PaymentPayMethod.transfer: 'TRANSFER',
  PaymentPayMethod.mobile: 'MOBILE',
  PaymentPayMethod.giftCertificate: 'GIFT_CERTIFICATE',
  PaymentPayMethod.easyPay: 'EASY_PAY',
  PaymentPayMethod.convenienceStore: 'CONVENIENCE_STORE',
};

const Map<PGCompany, String> _$PGCompanyEnumMap = {
  PGCompany.eximbayV2: 'eximbay_v2',
  PGCompany.hyphen: 'hyphen',
  PGCompany.inicisJp: 'inicis_jp',
  PGCompany.inicisV2: 'inicis_v2',
  PGCompany.kakaopay: 'kakaopay_payment',
  PGCompany.kcpV2: 'kcp_v2',
  PGCompany.kpn: 'kpn',
  PGCompany.ksnet: 'ksnet_payment',
  PGCompany.naverpay: 'naverpay_payment',
  PGCompany.niceV2: 'nice_v2_payment',
  PGCompany.payletterGlobal: 'payletter_global',
  PGCompany.smartroV2: 'smartro_v2_payment',
  PGCompany.tossBrandpay: 'toss_brandpay_payment',
  PGCompany.tosspayV2: 'tosspay_v2_payment',
  PGCompany.tosspayments: 'tosspayments_payment',
  PGCompany.tripleA: 'triple_a',
  PGCompany.welcome: 'welcome_payment',
};

const Map<PaymentLocale, String> _$PaymentLocaleEnumMap = {
  PaymentLocale.koKr: 'KO_KR',
  PaymentLocale.enUs: 'EN_US',
  PaymentLocale.zhCn: 'ZH_CN',
  PaymentLocale.zhTw: 'ZH_TW',
  PaymentLocale.jaJp: 'JA_JP',
  PaymentLocale.ruRu: 'RU_RU',
  PaymentLocale.thTh: 'TH_TH',
  PaymentLocale.viVn: 'VI_VN',
};

const Map<Country, String> _$CountryEnumMap = {
  Country.AF: 'COUNTRY_AF',
  Country.AX: 'COUNTRY_AX',
  Country.AL: 'COUNTRY_AL',
  Country.DZ: 'COUNTRY_DZ',
  Country.AS: 'COUNTRY_AS',
  Country.AD: 'COUNTRY_AD',
  Country.AO: 'COUNTRY_AO',
  Country.AI: 'COUNTRY_AI',
  Country.AQ: 'COUNTRY_AQ',
  Country.AG: 'COUNTRY_AG',
  Country.AR: 'COUNTRY_AR',
  Country.AM: 'COUNTRY_AM',
  Country.AW: 'COUNTRY_AW',
  Country.AU: 'COUNTRY_AU',
  Country.AT: 'COUNTRY_AT',
  Country.AZ: 'COUNTRY_AZ',
  Country.BH: 'COUNTRY_BH',
  Country.BS: 'COUNTRY_BS',
  Country.BD: 'COUNTRY_BD',
  Country.BB: 'COUNTRY_BB',
  Country.BY: 'COUNTRY_BY',
  Country.BE: 'COUNTRY_BE',
  Country.BZ: 'COUNTRY_BZ',
  Country.BJ: 'COUNTRY_BJ',
  Country.BM: 'COUNTRY_BM',
  Country.BT: 'COUNTRY_BT',
  Country.BO: 'COUNTRY_BO',
  Country.BQ: 'COUNTRY_BQ',
  Country.BA: 'COUNTRY_BA',
  Country.BW: 'COUNTRY_BW',
  Country.BV: 'COUNTRY_BV',
  Country.BR: 'COUNTRY_BR',
  Country.IO: 'COUNTRY_IO',
  Country.BN: 'COUNTRY_BN',
  Country.BG: 'COUNTRY_BG',
  Country.BF: 'COUNTRY_BF',
  Country.BI: 'COUNTRY_BI',
  Country.KH: 'COUNTRY_KH',
  Country.CM: 'COUNTRY_CM',
  Country.CA: 'COUNTRY_CA',
  Country.CV: 'COUNTRY_CV',
  Country.KY: 'COUNTRY_KY',
  Country.CF: 'COUNTRY_CF',
  Country.TD: 'COUNTRY_TD',
  Country.CL: 'COUNTRY_CL',
  Country.CN: 'COUNTRY_CN',
  Country.CX: 'COUNTRY_CX',
  Country.CC: 'COUNTRY_CC',
  Country.CO: 'COUNTRY_CO',
  Country.KM: 'COUNTRY_KM',
  Country.CG: 'COUNTRY_CG',
  Country.CD: 'COUNTRY_CD',
  Country.CK: 'COUNTRY_CK',
  Country.CR: 'COUNTRY_CR',
  Country.CI: 'COUNTRY_CI',
  Country.HR: 'COUNTRY_HR',
  Country.CU: 'COUNTRY_CU',
  Country.CW: 'COUNTRY_CW',
  Country.CY: 'COUNTRY_CY',
  Country.CZ: 'COUNTRY_CZ',
  Country.DK: 'COUNTRY_DK',
  Country.DJ: 'COUNTRY_DJ',
  Country.DM: 'COUNTRY_DM',
  Country.DO: 'COUNTRY_DO',
  Country.EC: 'COUNTRY_EC',
  Country.EG: 'COUNTRY_EG',
  Country.SV: 'COUNTRY_SV',
  Country.GQ: 'COUNTRY_GQ',
  Country.ER: 'COUNTRY_ER',
  Country.EE: 'COUNTRY_EE',
  Country.ET: 'COUNTRY_ET',
  Country.FK: 'COUNTRY_FK',
  Country.FO: 'COUNTRY_FO',
  Country.FJ: 'COUNTRY_FJ',
  Country.FI: 'COUNTRY_FI',
  Country.FR: 'COUNTRY_FR',
  Country.GF: 'COUNTRY_GF',
  Country.PF: 'COUNTRY_PF',
  Country.TF: 'COUNTRY_TF',
  Country.GA: 'COUNTRY_GA',
  Country.GM: 'COUNTRY_GM',
  Country.GE: 'COUNTRY_GE',
  Country.DE: 'COUNTRY_DE',
  Country.GH: 'COUNTRY_GH',
  Country.GI: 'COUNTRY_GI',
  Country.GR: 'COUNTRY_GR',
  Country.GL: 'COUNTRY_GL',
  Country.GD: 'COUNTRY_GD',
  Country.GP: 'COUNTRY_GP',
  Country.GU: 'COUNTRY_GU',
  Country.GT: 'COUNTRY_GT',
  Country.GG: 'COUNTRY_GG',
  Country.GN: 'COUNTRY_GN',
  Country.GW: 'COUNTRY_GW',
  Country.GY: 'COUNTRY_GY',
  Country.HT: 'COUNTRY_HT',
  Country.HM: 'COUNTRY_HM',
  Country.VA: 'COUNTRY_VA',
  Country.HN: 'COUNTRY_HN',
  Country.HK: 'COUNTRY_HK',
  Country.HU: 'COUNTRY_HU',
  Country.IS: 'COUNTRY_IS',
  Country.IN: 'COUNTRY_IN',
  Country.ID: 'COUNTRY_ID',
  Country.IR: 'COUNTRY_IR',
  Country.IQ: 'COUNTRY_IQ',
  Country.IE: 'COUNTRY_IE',
  Country.IM: 'COUNTRY_IM',
  Country.IL: 'COUNTRY_IL',
  Country.IT: 'COUNTRY_IT',
  Country.JM: 'COUNTRY_JM',
  Country.JP: 'COUNTRY_JP',
  Country.JE: 'COUNTRY_JE',
  Country.JO: 'COUNTRY_JO',
  Country.KZ: 'COUNTRY_KZ',
  Country.KE: 'COUNTRY_KE',
  Country.KI: 'COUNTRY_KI',
  Country.KP: 'COUNTRY_KP',
  Country.KR: 'COUNTRY_KR',
  Country.KW: 'COUNTRY_KW',
  Country.KG: 'COUNTRY_KG',
  Country.LA: 'COUNTRY_LA',
  Country.LV: 'COUNTRY_LV',
  Country.LB: 'COUNTRY_LB',
  Country.LS: 'COUNTRY_LS',
  Country.LR: 'COUNTRY_LR',
  Country.LY: 'COUNTRY_LY',
  Country.LI: 'COUNTRY_LI',
  Country.LT: 'COUNTRY_LT',
  Country.LU: 'COUNTRY_LU',
  Country.MO: 'COUNTRY_MO',
  Country.MK: 'COUNTRY_MK',
  Country.MG: 'COUNTRY_MG',
  Country.MW: 'COUNTRY_MW',
  Country.MY: 'COUNTRY_MY',
  Country.MV: 'COUNTRY_MV',
  Country.ML: 'COUNTRY_ML',
  Country.MT: 'COUNTRY_MT',
  Country.MH: 'COUNTRY_MH',
  Country.MQ: 'COUNTRY_MQ',
  Country.MR: 'COUNTRY_MR',
  Country.MU: 'COUNTRY_MU',
  Country.YT: 'COUNTRY_YT',
  Country.MX: 'COUNTRY_MX',
  Country.FM: 'COUNTRY_FM',
  Country.MD: 'COUNTRY_MD',
  Country.MC: 'COUNTRY_MC',
  Country.MN: 'COUNTRY_MN',
  Country.ME: 'COUNTRY_ME',
  Country.MS: 'COUNTRY_MS',
  Country.MA: 'COUNTRY_MA',
  Country.MZ: 'COUNTRY_MZ',
  Country.MM: 'COUNTRY_MM',
  Country.NA: 'COUNTRY_NA',
  Country.NR: 'COUNTRY_NR',
  Country.NP: 'COUNTRY_NP',
  Country.NL: 'COUNTRY_NL',
  Country.NC: 'COUNTRY_NC',
  Country.NZ: 'COUNTRY_NZ',
  Country.NI: 'COUNTRY_NI',
  Country.NE: 'COUNTRY_NE',
  Country.NG: 'COUNTRY_NG',
  Country.NU: 'COUNTRY_NU',
  Country.NF: 'COUNTRY_NF',
  Country.MP: 'COUNTRY_MP',
  Country.NO: 'COUNTRY_NO',
  Country.OM: 'COUNTRY_OM',
  Country.PK: 'COUNTRY_PK',
  Country.PW: 'COUNTRY_PW',
  Country.PS: 'COUNTRY_PS',
  Country.PA: 'COUNTRY_PA',
  Country.PG: 'COUNTRY_PG',
  Country.PY: 'COUNTRY_PY',
  Country.PE: 'COUNTRY_PE',
  Country.PH: 'COUNTRY_PH',
  Country.PN: 'COUNTRY_PN',
  Country.PL: 'COUNTRY_PL',
  Country.PT: 'COUNTRY_PT',
  Country.PR: 'COUNTRY_PR',
  Country.QA: 'COUNTRY_QA',
  Country.RE: 'COUNTRY_RE',
  Country.RO: 'COUNTRY_RO',
  Country.RU: 'COUNTRY_RU',
  Country.RW: 'COUNTRY_RW',
  Country.BL: 'COUNTRY_BL',
  Country.SH: 'COUNTRY_SH',
  Country.KN: 'COUNTRY_KN',
  Country.LC: 'COUNTRY_LC',
  Country.MF: 'COUNTRY_MF',
  Country.PM: 'COUNTRY_PM',
  Country.VC: 'COUNTRY_VC',
  Country.WS: 'COUNTRY_WS',
  Country.SM: 'COUNTRY_SM',
  Country.ST: 'COUNTRY_ST',
  Country.SA: 'COUNTRY_SA',
  Country.SN: 'COUNTRY_SN',
  Country.RS: 'COUNTRY_RS',
  Country.SC: 'COUNTRY_SC',
  Country.SL: 'COUNTRY_SL',
  Country.SG: 'COUNTRY_SG',
  Country.SX: 'COUNTRY_SX',
  Country.SK: 'COUNTRY_SK',
  Country.SI: 'COUNTRY_SI',
  Country.SB: 'COUNTRY_SB',
  Country.SO: 'COUNTRY_SO',
  Country.ZA: 'COUNTRY_ZA',
  Country.GS: 'COUNTRY_GS',
  Country.SS: 'COUNTRY_SS',
  Country.ES: 'COUNTRY_ES',
  Country.LK: 'COUNTRY_LK',
  Country.SD: 'COUNTRY_SD',
  Country.SR: 'COUNTRY_SR',
  Country.SJ: 'COUNTRY_SJ',
  Country.SZ: 'COUNTRY_SZ',
  Country.SE: 'COUNTRY_SE',
  Country.CH: 'COUNTRY_CH',
  Country.SY: 'COUNTRY_SY',
  Country.TW: 'COUNTRY_TW',
  Country.TJ: 'COUNTRY_TJ',
  Country.TZ: 'COUNTRY_TZ',
  Country.TH: 'COUNTRY_TH',
  Country.TL: 'COUNTRY_TL',
  Country.TG: 'COUNTRY_TG',
  Country.TK: 'COUNTRY_TK',
  Country.TO: 'COUNTRY_TO',
  Country.TT: 'COUNTRY_TT',
  Country.TN: 'COUNTRY_TN',
  Country.TR: 'COUNTRY_TR',
  Country.TM: 'COUNTRY_TM',
  Country.TC: 'COUNTRY_TC',
  Country.TV: 'COUNTRY_TV',
  Country.UG: 'COUNTRY_UG',
  Country.UA: 'COUNTRY_UA',
  Country.AE: 'COUNTRY_AE',
  Country.GB: 'COUNTRY_GB',
  Country.US: 'COUNTRY_US',
  Country.UM: 'COUNTRY_UM',
  Country.UY: 'COUNTRY_UY',
  Country.UZ: 'COUNTRY_UZ',
  Country.VU: 'COUNTRY_VU',
  Country.VE: 'COUNTRY_VE',
  Country.VN: 'COUNTRY_VN',
  Country.VG: 'COUNTRY_VG',
  Country.VI: 'COUNTRY_VI',
  Country.WF: 'COUNTRY_WF',
  Country.EH: 'COUNTRY_EH',
  Country.YE: 'COUNTRY_YE',
  Country.ZM: 'COUNTRY_ZM',
  Country.ZW: 'COUNTRY_ZW',
};

const Map<ProductType, String> _$ProductTypeEnumMap = {
  ProductType.digital: 'PRODUCT_TYPE_DIGITAL',
  ProductType.real: 'PRODUCT_TYPE_REAL',
};

const Map<CashReceiptTradeOption, String> _$CashReceiptTradeOptionEnumMap = {
  CashReceiptTradeOption.culture: 'CULTURE',
  CashReceiptTradeOption.general: 'GENERAL',
  CashReceiptTradeOption.publicTp: 'PUBLIC_TP',
};
