// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'payment_request.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PaymentRequest _$PaymentRequestFromJson(Map<String, dynamic> json) => $checkedCreate(
      'PaymentRequest',
      json,
      ($checkedConvert) {
        final val = PaymentRequest(
          storeId: $checkedConvert('storeId', (v) => v! as String),
          paymentId: $checkedConvert('paymentId', (v) => v! as String),
          orderName: $checkedConvert('orderName', (v) => v! as String),
          totalAmount: $checkedConvert('totalAmount', (v) => (v! as num).toInt()),
          currency: $checkedConvert('currency', (v) => $enumDecode(_$PaymentCurrencyEnumMap, v)),
          payMethod: $checkedConvert('payMethod', (v) => $enumDecode(_$PaymentPayMethodEnumMap, v)),
          channelKey: $checkedConvert('channelKey', (v) => v as String?),
          channelGroupId: $checkedConvert('channelGroupId', (v) => v as String?),
          taxFreeAmount: $checkedConvert('taxFreeAmount', (v) => (v as num?)?.toInt()),
          vatAmount: $checkedConvert('vatAmount', (v) => (v as num?)?.toInt()),
          customer: $checkedConvert('customer', (v) => v == null ? null : Customer.fromJson(v as Map<String, dynamic>)),
          customerId: $checkedConvert('customerId', (v) => v as String?),
          fullName: $checkedConvert('fullName', (v) => v as String?),
          firstName: $checkedConvert('firstName', (v) => v as String?),
          lastName: $checkedConvert('lastName', (v) => v as String?),
          phoneNumber: $checkedConvert('phoneNumber', (v) => v as String?),
          email: $checkedConvert('email', (v) => v as String?),
          address: $checkedConvert('address', (v) => v == null ? null : Address.fromJson(v as Map<String, dynamic>)),
          windowType:
              $checkedConvert('windowType', (v) => v == null ? null : WindowTypes.fromJson(v as Map<String, dynamic>)),
          redirectUrl: $checkedConvert('redirectUrl', (v) => v as String?),
          noticeUrls: $checkedConvert('noticeUrls', (v) => (v as List<dynamic>?)?.map((e) => e as String).toList()),
          confirmUrl: $checkedConvert('confirmUrl', (v) => v as String?),
          appScheme: $checkedConvert('appScheme', (v) => v as String?),
          isEscrow: $checkedConvert('isEscrow', (v) => v as bool? ?? false),
          products: $checkedConvert(
            'products',
            (v) => (v as List<dynamic>?)?.map((e) => ProductDetail.fromJson(e as Map<String, dynamic>)).toList(),
          ),
          locale: $checkedConvert('locale', (v) => $enumDecodeNullable(_$PaymentLocaleEnumMap, v)),
          customData: $checkedConvert(
            'customData',
            (v) => (v as Map<String, dynamic>?)?.map(
              (k, e) => MapEntry(k, e as String),
            ),
          ),
          isCulturalExpense: $checkedConvert('isCulturalExpense', (v) => v as bool?),
          bypass:
              $checkedConvert('bypass', (v) => v == null ? null : PaymentBypass.fromJson(v as Map<String, dynamic>)),
          country: $checkedConvert('country', (v) => $enumDecodeNullable(_$CountryEnumMap, v)),
          productType: $checkedConvert('productType', (v) => $enumDecodeNullable(_$ProductTypeEnumMap, v)),
          expiredTime: $checkedConvert('expiredTime', (v) => v as String?),
          cashReceiptTradeOption:
              $checkedConvert('cashReceiptTradeOption', (v) => $enumDecodeNullable(_$CashReceiptTradeOptionEnumMap, v)),
          offerPeriod:
              $checkedConvert('offerPeriod', (v) => v == null ? null : OfferPeriod.fromJson(v as Map<String, dynamic>)),
          storeDetails: $checkedConvert(
            'storeDetails',
            (v) => v == null ? null : StoreDetails.fromJson(v as Map<String, dynamic>),
          ),
          shippingAddress:
              $checkedConvert('shippingAddress', (v) => v == null ? null : Address.fromJson(v as Map<String, dynamic>)),
          promotionId: $checkedConvert('promotionId', (v) => v as String?),
          popup: $checkedConvert('popup', (v) => v == null ? null : Popup.fromJson(v as Map<String, dynamic>)),
        );
        return val;
      },
    );

Map<String, dynamic> _$PaymentRequestToJson(PaymentRequest instance) => <String, dynamic>{
      'storeId': instance.storeId,
      'paymentId': instance.paymentId,
      'orderName': instance.orderName,
      'totalAmount': instance.totalAmount,
      'currency': _$PaymentCurrencyEnumMap[instance.currency],
      'payMethod': _$PaymentPayMethodEnumMap[instance.payMethod],
      if (instance.channelKey case final value?) 'channelKey': value,
      if (instance.channelGroupId case final value?) 'channelGroupId': value,
      if (instance.taxFreeAmount case final value?) 'taxFreeAmount': value,
      if (instance.vatAmount case final value?) 'vatAmount': value,
      if (instance.customer?.toJson() case final value?) 'customer': value,
      if (instance.customerId case final value?) 'customerId': value,
      if (instance.fullName case final value?) 'fullName': value,
      if (instance.firstName case final value?) 'firstName': value,
      if (instance.lastName case final value?) 'lastName': value,
      if (instance.phoneNumber case final value?) 'phoneNumber': value,
      if (instance.email case final value?) 'email': value,
      if (instance.address?.toJson() case final value?) 'address': value,
      if (instance.windowType?.toJson() case final value?) 'windowType': value,
      if (instance.redirectUrl case final value?) 'redirectUrl': value,
      if (instance.noticeUrls case final value?) 'noticeUrls': value,
      if (instance.confirmUrl case final value?) 'confirmUrl': value,
      if (instance.appScheme case final value?) 'appScheme': value,
      'isEscrow': instance.isEscrow,
      if (instance.products?.map((e) => e.toJson()).toList() case final value?) 'products': value,
      if (instance.isCulturalExpense case final value?) 'isCulturalExpense': value,
      if (_$PaymentLocaleEnumMap[instance.locale] case final value?) 'locale': value,
      if (instance.customData case final value?) 'customData': value,
      if (instance.expiredTime case final value?) 'expiredTime': value,
      if (instance.bypass?.toJson() case final value?) 'bypass': value,
      if (_$CountryEnumMap[instance.country] case final value?) 'country': value,
      if (_$ProductTypeEnumMap[instance.productType] case final value?) 'productType': value,
      if (_$CashReceiptTradeOptionEnumMap[instance.cashReceiptTradeOption] case final value?)
        'cashReceiptTradeOption': value,
      if (instance.offerPeriod?.toJson() case final value?) 'offerPeriod': value,
      if (instance.storeDetails?.toJson() case final value?) 'storeDetails': value,
      if (instance.shippingAddress?.toJson() case final value?) 'shippingAddress': value,
      if (instance.promotionId case final value?) 'promotionId': value,
      if (instance.popup?.toJson() case final value?) 'popup': value,
    };

const _$PaymentCurrencyEnumMap = {
  PaymentCurrency.krw: 'CURRENCY_KRW',
  PaymentCurrency.usd: 'CURRENCY_USD',
  PaymentCurrency.eur: 'CURRENCY_EUR',
  PaymentCurrency.jpy: 'CURRENCY_JPY',
  PaymentCurrency.cny: 'CURRENCY_CNY',
  PaymentCurrency.vnd: 'CURRENCY_VND',
  PaymentCurrency.thb: 'CURRENCY_THB',
  PaymentCurrency.sgd: 'CURRENCY_SGD',
  PaymentCurrency.aud: 'CURRENCY_AUD',
  PaymentCurrency.hkd: 'CURRENCY_HKD',
  PaymentCurrency.aed: 'CURRENCY_AED',
  PaymentCurrency.afn: 'CURRENCY_AFN',
  PaymentCurrency.all: 'CURRENCY_ALL',
  PaymentCurrency.amd: 'CURRENCY_AMD',
  PaymentCurrency.ang: 'CURRENCY_ANG',
  PaymentCurrency.aoa: 'CURRENCY_AOA',
  PaymentCurrency.ars: 'CURRENCY_ARS',
  PaymentCurrency.awg: 'CURRENCY_AWG',
  PaymentCurrency.azn: 'CURRENCY_AZN',
  PaymentCurrency.bam: 'CURRENCY_BAM',
  PaymentCurrency.bbd: 'CURRENCY_BBD',
  PaymentCurrency.bdt: 'CURRENCY_BDT',
  PaymentCurrency.bgn: 'CURRENCY_BGN',
  PaymentCurrency.bhd: 'CURRENCY_BHD',
  PaymentCurrency.bif: 'CURRENCY_BIF',
  PaymentCurrency.bmd: 'CURRENCY_BMD',
  PaymentCurrency.bnd: 'CURRENCY_BND',
  PaymentCurrency.bob: 'CURRENCY_BOB',
  PaymentCurrency.bov: 'CURRENCY_BOV',
  PaymentCurrency.brl: 'CURRENCY_BRL',
  PaymentCurrency.bsd: 'CURRENCY_BSD',
  PaymentCurrency.btn: 'CURRENCY_BTN',
  PaymentCurrency.bwp: 'CURRENCY_BWP',
  PaymentCurrency.byn: 'CURRENCY_BYN',
  PaymentCurrency.bzd: 'CURRENCY_BZD',
  PaymentCurrency.cad: 'CURRENCY_CAD',
  PaymentCurrency.cdf: 'CURRENCY_CDF',
  PaymentCurrency.che: 'CURRENCY_CHE',
  PaymentCurrency.chf: 'CURRENCY_CHF',
  PaymentCurrency.chw: 'CURRENCY_CHW',
  PaymentCurrency.clf: 'CURRENCY_CLF',
  PaymentCurrency.clp: 'CURRENCY_CLP',
  PaymentCurrency.cop: 'CURRENCY_COP',
  PaymentCurrency.cou: 'CURRENCY_COU',
  PaymentCurrency.crc: 'CURRENCY_CRC',
  PaymentCurrency.cuc: 'CURRENCY_CUC',
  PaymentCurrency.cup: 'CURRENCY_CUP',
  PaymentCurrency.cve: 'CURRENCY_CVE',
  PaymentCurrency.czk: 'CURRENCY_CZK',
  PaymentCurrency.djf: 'CURRENCY_DJF',
  PaymentCurrency.dkk: 'CURRENCY_DKK',
  PaymentCurrency.dop: 'CURRENCY_DOP',
  PaymentCurrency.dzd: 'CURRENCY_DZD',
  PaymentCurrency.egp: 'CURRENCY_EGP',
  PaymentCurrency.ern: 'CURRENCY_ERN',
  PaymentCurrency.etb: 'CURRENCY_ETB',
  PaymentCurrency.fjd: 'CURRENCY_FJD',
  PaymentCurrency.fkp: 'CURRENCY_FKP',
  PaymentCurrency.gbp: 'CURRENCY_GBP',
  PaymentCurrency.gel: 'CURRENCY_GEL',
  PaymentCurrency.ghs: 'CURRENCY_GHS',
  PaymentCurrency.gip: 'CURRENCY_GIP',
  PaymentCurrency.gmd: 'CURRENCY_GMD',
  PaymentCurrency.gnf: 'CURRENCY_GNF',
  PaymentCurrency.gtq: 'CURRENCY_GTQ',
  PaymentCurrency.gyd: 'CURRENCY_GYD',
  PaymentCurrency.hnl: 'CURRENCY_HNL',
  PaymentCurrency.hrk: 'CURRENCY_HRK',
  PaymentCurrency.htg: 'CURRENCY_HTG',
  PaymentCurrency.huf: 'CURRENCY_HUF',
  PaymentCurrency.idr: 'CURRENCY_IDR',
  PaymentCurrency.ils: 'CURRENCY_ILS',
  PaymentCurrency.inr: 'CURRENCY_INR',
  PaymentCurrency.iqd: 'CURRENCY_IQD',
  PaymentCurrency.irr: 'CURRENCY_IRR',
  PaymentCurrency.isk: 'CURRENCY_ISK',
  PaymentCurrency.jmd: 'CURRENCY_JMD',
  PaymentCurrency.jod: 'CURRENCY_JOD',
  PaymentCurrency.kes: 'CURRENCY_KES',
  PaymentCurrency.kgs: 'CURRENCY_KGS',
  PaymentCurrency.khr: 'CURRENCY_KHR',
  PaymentCurrency.kmf: 'CURRENCY_KMF',
  PaymentCurrency.kpw: 'CURRENCY_KPW',
  PaymentCurrency.kwd: 'CURRENCY_KWD',
  PaymentCurrency.kyd: 'CURRENCY_KYD',
  PaymentCurrency.kzt: 'CURRENCY_KZT',
  PaymentCurrency.lak: 'CURRENCY_LAK',
  PaymentCurrency.lbp: 'CURRENCY_LBP',
  PaymentCurrency.lkr: 'CURRENCY_LKR',
  PaymentCurrency.lrd: 'CURRENCY_LRD',
  PaymentCurrency.lsl: 'CURRENCY_LSL',
  PaymentCurrency.lyd: 'CURRENCY_LYD',
  PaymentCurrency.mad: 'CURRENCY_MAD',
  PaymentCurrency.mdl: 'CURRENCY_MDL',
  PaymentCurrency.mga: 'CURRENCY_MGA',
  PaymentCurrency.mkd: 'CURRENCY_MKD',
  PaymentCurrency.mmk: 'CURRENCY_MMK',
  PaymentCurrency.mnt: 'CURRENCY_MNT',
  PaymentCurrency.mop: 'CURRENCY_MOP',
  PaymentCurrency.mru: 'CURRENCY_MRU',
  PaymentCurrency.mur: 'CURRENCY_MUR',
  PaymentCurrency.mvr: 'CURRENCY_MVR',
  PaymentCurrency.mwk: 'CURRENCY_MWK',
  PaymentCurrency.mxn: 'CURRENCY_MXN',
  PaymentCurrency.mxv: 'CURRENCY_MXV',
  PaymentCurrency.mzn: 'CURRENCY_MZN',
  PaymentCurrency.nad: 'CURRENCY_NAD',
  PaymentCurrency.ngn: 'CURRENCY_NGN',
  PaymentCurrency.nio: 'CURRENCY_NIO',
  PaymentCurrency.nok: 'CURRENCY_NOK',
  PaymentCurrency.npr: 'CURRENCY_NPR',
  PaymentCurrency.nzd: 'CURRENCY_NZD',
  PaymentCurrency.omr: 'CURRENCY_OMR',
  PaymentCurrency.pab: 'CURRENCY_PAB',
  PaymentCurrency.pen: 'CURRENCY_PEN',
  PaymentCurrency.pgk: 'CURRENCY_PGK',
  PaymentCurrency.php: 'CURRENCY_PHP',
  PaymentCurrency.pkr: 'CURRENCY_PKR',
  PaymentCurrency.pln: 'CURRENCY_PLN',
  PaymentCurrency.pyg: 'CURRENCY_PYG',
  PaymentCurrency.qar: 'CURRENCY_QAR',
  PaymentCurrency.ron: 'CURRENCY_RON',
  PaymentCurrency.rsd: 'CURRENCY_RSD',
  PaymentCurrency.rub: 'CURRENCY_RUB',
  PaymentCurrency.rwf: 'CURRENCY_RWF',
  PaymentCurrency.sar: 'CURRENCY_SAR',
  PaymentCurrency.sbd: 'CURRENCY_SBD',
  PaymentCurrency.scr: 'CURRENCY_SCR',
  PaymentCurrency.sdg: 'CURRENCY_SDG',
  PaymentCurrency.sek: 'CURRENCY_SEK',
  PaymentCurrency.shp: 'CURRENCY_SHP',
  PaymentCurrency.sle: 'CURRENCY_SLE',
  PaymentCurrency.sll: 'CURRENCY_SLL',
  PaymentCurrency.sos: 'CURRENCY_SOS',
  PaymentCurrency.srd: 'CURRENCY_SRD',
  PaymentCurrency.ssp: 'CURRENCY_SSP',
  PaymentCurrency.stn: 'CURRENCY_STN',
  PaymentCurrency.svc: 'CURRENCY_SVC',
  PaymentCurrency.syp: 'CURRENCY_SYP',
  PaymentCurrency.szl: 'CURRENCY_SZL',
  PaymentCurrency.tjs: 'CURRENCY_TJS',
  PaymentCurrency.tmt: 'CURRENCY_TMT',
  PaymentCurrency.tnd: 'CURRENCY_TND',
  PaymentCurrency.top: 'CURRENCY_TOP',
  PaymentCurrency.TRY: 'CURRENCY_TRY',
  PaymentCurrency.ttd: 'CURRENCY_TTD',
  PaymentCurrency.twd: 'CURRENCY_TWD',
  PaymentCurrency.tzs: 'CURRENCY_TZS',
  PaymentCurrency.uah: 'CURRENCY_UAH',
  PaymentCurrency.ugx: 'CURRENCY_UGX',
  PaymentCurrency.usn: 'CURRENCY_USN',
  PaymentCurrency.uyi: 'CURRENCY_UYI',
  PaymentCurrency.uyu: 'CURRENCY_UYU',
  PaymentCurrency.uyw: 'CURRENCY_UYW',
  PaymentCurrency.uzs: 'CURRENCY_UZS',
  PaymentCurrency.ved: 'CURRENCY_VED',
  PaymentCurrency.ves: 'CURRENCY_VES',
  PaymentCurrency.vuv: 'CURRENCY_VUV',
  PaymentCurrency.wst: 'CURRENCY_WST',
  PaymentCurrency.xaf: 'CURRENCY_XAF',
  PaymentCurrency.xag: 'CURRENCY_XAG',
  PaymentCurrency.xau: 'CURRENCY_XAU',
  PaymentCurrency.xba: 'CURRENCY_XBA',
  PaymentCurrency.xbb: 'CURRENCY_XBB',
  PaymentCurrency.xbc: 'CURRENCY_XBC',
  PaymentCurrency.xbd: 'CURRENCY_XBD',
  PaymentCurrency.xcd: 'CURRENCY_XCD',
  PaymentCurrency.xdr: 'CURRENCY_XDR',
  PaymentCurrency.xof: 'CURRENCY_XOF',
  PaymentCurrency.xpd: 'CURRENCY_XPD',
  PaymentCurrency.xpf: 'CURRENCY_XPF',
  PaymentCurrency.xpt: 'CURRENCY_XPT',
  PaymentCurrency.xsu: 'CURRENCY_XSU',
  PaymentCurrency.xts: 'CURRENCY_XTS',
  PaymentCurrency.xua: 'CURRENCY_XUA',
  PaymentCurrency.xxx: 'CURRENCY_XXX',
  PaymentCurrency.yer: 'CURRENCY_YER',
  PaymentCurrency.zar: 'CURRENCY_ZAR',
  PaymentCurrency.zmw: 'CURRENCY_ZMW',
  PaymentCurrency.zwl: 'CURRENCY_ZWL',
};

const _$PaymentPayMethodEnumMap = {
  PaymentPayMethod.card: 'CARD',
  PaymentPayMethod.virtualAccount: 'VIRTUAL_ACCOUNT',
  PaymentPayMethod.transfer: 'TRANSFER',
  PaymentPayMethod.mobile: 'MOBILE',
  PaymentPayMethod.giftCertificate: 'GIFT_CERTIFICATE',
  PaymentPayMethod.easyPay: 'EASY_PAY',
  PaymentPayMethod.paypal: 'PAYPAL',
};

const _$PaymentLocaleEnumMap = {
  PaymentLocale.koKr: 'KO_KR',
  PaymentLocale.enUs: 'EN_US',
  PaymentLocale.zhCn: 'ZH_CN',
  PaymentLocale.zhTw: 'ZH_TW',
  PaymentLocale.jaJp: 'JA_JP',
  PaymentLocale.ruRu: 'RU_RU',
  PaymentLocale.thTh: 'TH_TH',
  PaymentLocale.viVn: 'VI_VN',
};

const _$CountryEnumMap = {
  Country.AF: 'COUNTRY_AF',
  Country.AX: 'COUNTRY_AX',
  Country.AL: 'COUNTRY_AL',
  Country.DZ: 'COUNTRY_DZ',
  Country.AS: 'COUNTRY_AS',
  Country.AD: 'COUNTRY_AD',
  Country.AO: 'COUNTRY_AO',
  Country.AI: 'COUNTRY_AI',
  Country.AQ: 'COUNTRY_AQ',
  Country.AG: 'COUNTRY_AG',
  Country.AR: 'COUNTRY_AR',
  Country.AM: 'COUNTRY_AM',
  Country.AW: 'COUNTRY_AW',
  Country.AU: 'COUNTRY_AU',
  Country.AT: 'COUNTRY_AT',
  Country.AZ: 'COUNTRY_AZ',
  Country.BH: 'COUNTRY_BH',
  Country.BS: 'COUNTRY_BS',
  Country.BD: 'COUNTRY_BD',
  Country.BB: 'COUNTRY_BB',
  Country.BY: 'COUNTRY_BY',
  Country.BE: 'COUNTRY_BE',
  Country.BZ: 'COUNTRY_BZ',
  Country.BJ: 'COUNTRY_BJ',
  Country.BM: 'COUNTRY_BM',
  Country.BT: 'COUNTRY_BT',
  Country.BO: 'COUNTRY_BO',
  Country.BQ: 'COUNTRY_BQ',
  Country.BA: 'COUNTRY_BA',
  Country.BW: 'COUNTRY_BW',
  Country.BV: 'COUNTRY_BV',
  Country.BR: 'COUNTRY_BR',
  Country.IO: 'COUNTRY_IO',
  Country.BN: 'COUNTRY_BN',
  Country.BG: 'COUNTRY_BG',
  Country.BF: 'COUNTRY_BF',
  Country.BI: 'COUNTRY_BI',
  Country.KH: 'COUNTRY_KH',
  Country.CM: 'COUNTRY_CM',
  Country.CA: 'COUNTRY_CA',
  Country.CV: 'COUNTRY_CV',
  Country.KY: 'COUNTRY_KY',
  Country.CF: 'COUNTRY_CF',
  Country.TD: 'COUNTRY_TD',
  Country.CL: 'COUNTRY_CL',
  Country.CN: 'COUNTRY_CN',
  Country.CX: 'COUNTRY_CX',
  Country.CC: 'COUNTRY_CC',
  Country.CO: 'COUNTRY_CO',
  Country.KM: 'COUNTRY_KM',
  Country.CG: 'COUNTRY_CG',
  Country.CD: 'COUNTRY_CD',
  Country.CK: 'COUNTRY_CK',
  Country.CR: 'COUNTRY_CR',
  Country.CI: 'COUNTRY_CI',
  Country.HR: 'COUNTRY_HR',
  Country.CU: 'COUNTRY_CU',
  Country.CW: 'COUNTRY_CW',
  Country.CY: 'COUNTRY_CY',
  Country.CZ: 'COUNTRY_CZ',
  Country.DK: 'COUNTRY_DK',
  Country.DJ: 'COUNTRY_DJ',
  Country.DM: 'COUNTRY_DM',
  Country.DO: 'COUNTRY_DO',
  Country.EC: 'COUNTRY_EC',
  Country.EG: 'COUNTRY_EG',
  Country.SV: 'COUNTRY_SV',
  Country.GQ: 'COUNTRY_GQ',
  Country.ER: 'COUNTRY_ER',
  Country.EE: 'COUNTRY_EE',
  Country.ET: 'COUNTRY_ET',
  Country.FK: 'COUNTRY_FK',
  Country.FO: 'COUNTRY_FO',
  Country.FJ: 'COUNTRY_FJ',
  Country.FI: 'COUNTRY_FI',
  Country.FR: 'COUNTRY_FR',
  Country.GF: 'COUNTRY_GF',
  Country.PF: 'COUNTRY_PF',
  Country.TF: 'COUNTRY_TF',
  Country.GA: 'COUNTRY_GA',
  Country.GM: 'COUNTRY_GM',
  Country.GE: 'COUNTRY_GE',
  Country.DE: 'COUNTRY_DE',
  Country.GH: 'COUNTRY_GH',
  Country.GI: 'COUNTRY_GI',
  Country.GR: 'COUNTRY_GR',
  Country.GL: 'COUNTRY_GL',
  Country.GD: 'COUNTRY_GD',
  Country.GP: 'COUNTRY_GP',
  Country.GU: 'COUNTRY_GU',
  Country.GT: 'COUNTRY_GT',
  Country.GG: 'COUNTRY_GG',
  Country.GN: 'COUNTRY_GN',
  Country.GW: 'COUNTRY_GW',
  Country.GY: 'COUNTRY_GY',
  Country.HT: 'COUNTRY_HT',
  Country.HM: 'COUNTRY_HM',
  Country.VA: 'COUNTRY_VA',
  Country.HN: 'COUNTRY_HN',
  Country.HK: 'COUNTRY_HK',
  Country.HU: 'COUNTRY_HU',
  Country.IS: 'COUNTRY_IS',
  Country.IN: 'COUNTRY_IN',
  Country.ID: 'COUNTRY_ID',
  Country.IR: 'COUNTRY_IR',
  Country.IQ: 'COUNTRY_IQ',
  Country.IE: 'COUNTRY_IE',
  Country.IM: 'COUNTRY_IM',
  Country.IL: 'COUNTRY_IL',
  Country.IT: 'COUNTRY_IT',
  Country.JM: 'COUNTRY_JM',
  Country.JP: 'COUNTRY_JP',
  Country.JE: 'COUNTRY_JE',
  Country.JO: 'COUNTRY_JO',
  Country.KZ: 'COUNTRY_KZ',
  Country.KE: 'COUNTRY_KE',
  Country.KI: 'COUNTRY_KI',
  Country.KP: 'COUNTRY_KP',
  Country.KR: 'COUNTRY_KR',
  Country.KW: 'COUNTRY_KW',
  Country.KG: 'COUNTRY_KG',
  Country.LA: 'COUNTRY_LA',
  Country.LV: 'COUNTRY_LV',
  Country.LB: 'COUNTRY_LB',
  Country.LS: 'COUNTRY_LS',
  Country.LR: 'COUNTRY_LR',
  Country.LY: 'COUNTRY_LY',
  Country.LI: 'COUNTRY_LI',
  Country.LT: 'COUNTRY_LT',
  Country.LU: 'COUNTRY_LU',
  Country.MO: 'COUNTRY_MO',
  Country.MK: 'COUNTRY_MK',
  Country.MG: 'COUNTRY_MG',
  Country.MW: 'COUNTRY_MW',
  Country.MY: 'COUNTRY_MY',
  Country.MV: 'COUNTRY_MV',
  Country.ML: 'COUNTRY_ML',
  Country.MT: 'COUNTRY_MT',
  Country.MH: 'COUNTRY_MH',
  Country.MQ: 'COUNTRY_MQ',
  Country.MR: 'COUNTRY_MR',
  Country.MU: 'COUNTRY_MU',
  Country.YT: 'COUNTRY_YT',
  Country.MX: 'COUNTRY_MX',
  Country.FM: 'COUNTRY_FM',
  Country.MD: 'COUNTRY_MD',
  Country.MC: 'COUNTRY_MC',
  Country.MN: 'COUNTRY_MN',
  Country.ME: 'COUNTRY_ME',
  Country.MS: 'COUNTRY_MS',
  Country.MA: 'COUNTRY_MA',
  Country.MZ: 'COUNTRY_MZ',
  Country.MM: 'COUNTRY_MM',
  Country.NA: 'COUNTRY_NA',
  Country.NR: 'COUNTRY_NR',
  Country.NP: 'COUNTRY_NP',
  Country.NL: 'COUNTRY_NL',
  Country.NC: 'COUNTRY_NC',
  Country.NZ: 'COUNTRY_NZ',
  Country.NI: 'COUNTRY_NI',
  Country.NE: 'COUNTRY_NE',
  Country.NG: 'COUNTRY_NG',
  Country.NU: 'COUNTRY_NU',
  Country.NF: 'COUNTRY_NF',
  Country.MP: 'COUNTRY_MP',
  Country.NO: 'COUNTRY_NO',
  Country.OM: 'COUNTRY_OM',
  Country.PK: 'COUNTRY_PK',
  Country.PW: 'COUNTRY_PW',
  Country.PS: 'COUNTRY_PS',
  Country.PA: 'COUNTRY_PA',
  Country.PG: 'COUNTRY_PG',
  Country.PY: 'COUNTRY_PY',
  Country.PE: 'COUNTRY_PE',
  Country.PH: 'COUNTRY_PH',
  Country.PN: 'COUNTRY_PN',
  Country.PL: 'COUNTRY_PL',
  Country.PT: 'COUNTRY_PT',
  Country.PR: 'COUNTRY_PR',
  Country.QA: 'COUNTRY_QA',
  Country.RE: 'COUNTRY_RE',
  Country.RO: 'COUNTRY_RO',
  Country.RU: 'COUNTRY_RU',
  Country.RW: 'COUNTRY_RW',
  Country.BL: 'COUNTRY_BL',
  Country.SH: 'COUNTRY_SH',
  Country.KN: 'COUNTRY_KN',
  Country.LC: 'COUNTRY_LC',
  Country.MF: 'COUNTRY_MF',
  Country.PM: 'COUNTRY_PM',
  Country.VC: 'COUNTRY_VC',
  Country.WS: 'COUNTRY_WS',
  Country.SM: 'COUNTRY_SM',
  Country.ST: 'COUNTRY_ST',
  Country.SA: 'COUNTRY_SA',
  Country.SN: 'COUNTRY_SN',
  Country.RS: 'COUNTRY_RS',
  Country.SC: 'COUNTRY_SC',
  Country.SL: 'COUNTRY_SL',
  Country.SG: 'COUNTRY_SG',
  Country.SX: 'COUNTRY_SX',
  Country.SK: 'COUNTRY_SK',
  Country.SI: 'COUNTRY_SI',
  Country.SB: 'COUNTRY_SB',
  Country.SO: 'COUNTRY_SO',
  Country.ZA: 'COUNTRY_ZA',
  Country.GS: 'COUNTRY_GS',
  Country.SS: 'COUNTRY_SS',
  Country.ES: 'COUNTRY_ES',
  Country.LK: 'COUNTRY_LK',
  Country.SD: 'COUNTRY_SD',
  Country.SR: 'COUNTRY_SR',
  Country.SJ: 'COUNTRY_SJ',
  Country.SZ: 'COUNTRY_SZ',
  Country.SE: 'COUNTRY_SE',
  Country.CH: 'COUNTRY_CH',
  Country.SY: 'COUNTRY_SY',
  Country.TW: 'COUNTRY_TW',
  Country.TJ: 'COUNTRY_TJ',
  Country.TZ: 'COUNTRY_TZ',
  Country.TH: 'COUNTRY_TH',
  Country.TL: 'COUNTRY_TL',
  Country.TG: 'COUNTRY_TG',
  Country.TK: 'COUNTRY_TK',
  Country.TO: 'COUNTRY_TO',
  Country.TT: 'COUNTRY_TT',
  Country.TN: 'COUNTRY_TN',
  Country.TR: 'COUNTRY_TR',
  Country.TM: 'COUNTRY_TM',
  Country.TC: 'COUNTRY_TC',
  Country.TV: 'COUNTRY_TV',
  Country.UG: 'COUNTRY_UG',
  Country.UA: 'COUNTRY_UA',
  Country.AE: 'COUNTRY_AE',
  Country.GB: 'COUNTRY_GB',
  Country.US: 'COUNTRY_US',
  Country.UM: 'COUNTRY_UM',
  Country.UY: 'COUNTRY_UY',
  Country.UZ: 'COUNTRY_UZ',
  Country.VU: 'COUNTRY_VU',
  Country.VE: 'COUNTRY_VE',
  Country.VN: 'COUNTRY_VN',
  Country.VG: 'COUNTRY_VG',
  Country.VI: 'COUNTRY_VI',
  Country.WF: 'COUNTRY_WF',
  Country.EH: 'COUNTRY_EH',
  Country.YE: 'COUNTRY_YE',
  Country.ZM: 'COUNTRY_ZM',
  Country.ZW: 'COUNTRY_ZW',
};

const _$ProductTypeEnumMap = {
  ProductType.digital: 'PRODUCT_TYPE_DIGITAL',
  ProductType.real: 'PRODUCT_TYPE_REAL',
};

const _$CashReceiptTradeOptionEnumMap = {
  CashReceiptTradeOption.CULTURE: 'CULTURE',
  CashReceiptTradeOption.GENERAL: 'GENERAL',
  CashReceiptTradeOption.PUBLIC_TP: 'PUBLIC_TP',
};
