// 📦 Package imports:
import 'package:json_annotation/json_annotation.dart';

/// 결제 통화 enum
@JsonEnum()
enum PaymentCurrency {
  @JsonValue('CURRENCY_KRW')
  KRW,
  @JsonValue('CURRENCY_USD')
  USD,
  @JsonValue('CURRENCY_EUR')
  EUR,
  @JsonValue('CURRENCY_JPY')
  JPY,
  @JsonValue('CURRENCY_CNY')
  CNY,
  @JsonValue('CURRENCY_VND')
  VND,
  @JsonValue('CURRENCY_THB')
  THB,
  @JsonValue('CURRENCY_SGD')
  SGD,
  @JsonValue('CURRENCY_AUD')
  AUD,
  @JsonValue('CURRENCY_HKD')
  HKD,
  @JsonValue('CURRENCY_AED')
  AED,
  @JsonValue('CURRENCY_AFN')
  AFN,
  @JsonValue('CURRENCY_ALL')
  ALL,
  @JsonValue('CURRENCY_AMD')
  AMD,
  @JsonValue('CURRENCY_ANG')
  ANG,
  @JsonValue('CURRENCY_AOA')
  AOA,
  @JsonValue('CURRENCY_ARS')
  ARS,
  @JsonValue('CURRENCY_AWG')
  AWG,
  @JsonValue('CURRENCY_AZN')
  AZN,
  @JsonValue('CURRENCY_BAM')
  BAM,
  @JsonValue('CURRENCY_BBD')
  BBD,
  @JsonValue('CURRENCY_BDT')
  BDT,
  @JsonValue('CURRENCY_BGN')
  BGN,
  @JsonValue('CURRENCY_BHD')
  BHD,
  @JsonValue('CURRENCY_BIF')
  BIF,
  @JsonValue('CURRENCY_BMD')
  BMD,
  @JsonValue('CURRENCY_BND')
  BND,
  @JsonValue('CURRENCY_BOB')
  BOB,
  @JsonValue('CURRENCY_BOV')
  BOV,
  @JsonValue('CURRENCY_BRL')
  BRL,
  @JsonValue('CURRENCY_BSD')
  BSD,
  @JsonValue('CURRENCY_BTN')
  BTN,
  @JsonValue('CURRENCY_BWP')
  BWP,
  @JsonValue('CURRENCY_BYN')
  BYN,
  @JsonValue('CURRENCY_BZD')
  BZD,
  @JsonValue('CURRENCY_CAD')
  CAD,
  @JsonValue('CURRENCY_CDF')
  CDF,
  @JsonValue('CURRENCY_CHE')
  CHE,
  @JsonValue('CURRENCY_CHF')
  CHF,
  @JsonValue('CURRENCY_CHW')
  CHW,
  @JsonValue('CURRENCY_CLF')
  CLF,
  @JsonValue('CURRENCY_CLP')
  CLP,
  @JsonValue('CURRENCY_COP')
  COP,
  @JsonValue('CURRENCY_COU')
  COU,
  @JsonValue('CURRENCY_CRC')
  CRC,
  @JsonValue('CURRENCY_CUC')
  CUC,
  @JsonValue('CURRENCY_CUP')
  CUP,
  @JsonValue('CURRENCY_CVE')
  CVE,
  @JsonValue('CURRENCY_CZK')
  CZK,
  @JsonValue('CURRENCY_DJF')
  DJF,
  @JsonValue('CURRENCY_DKK')
  DKK,
  @JsonValue('CURRENCY_DOP')
  DOP,
  @JsonValue('CURRENCY_DZD')
  DZD,
  @JsonValue('CURRENCY_EGP')
  EGP,
  @JsonValue('CURRENCY_ERN')
  ERN,
  @JsonValue('CURRENCY_ETB')
  ETB,
  @JsonValue('CURRENCY_FJD')
  FJD,
  @JsonValue('CURRENCY_FKP')
  FKP,
  @JsonValue('CURRENCY_GBP')
  GBP,
  @JsonValue('CURRENCY_GEL')
  GEL,
  @JsonValue('CURRENCY_GHS')
  GHS,
  @JsonValue('CURRENCY_GIP')
  GIP,
  @JsonValue('CURRENCY_GMD')
  GMD,
  @JsonValue('CURRENCY_GNF')
  GNF,
  @JsonValue('CURRENCY_GTQ')
  GTQ,
  @JsonValue('CURRENCY_GYD')
  GYD,
  @JsonValue('CURRENCY_HNL')
  HNL,
  @JsonValue('CURRENCY_HRK')
  HRK,
  @JsonValue('CURRENCY_HTG')
  HTG,
  @JsonValue('CURRENCY_HUF')
  HUF,
  @JsonValue('CURRENCY_IDR')
  IDR,
  @JsonValue('CURRENCY_ILS')
  ILS,
  @JsonValue('CURRENCY_INR')
  INR,
  @JsonValue('CURRENCY_IQD')
  IQD,
  @JsonValue('CURRENCY_IRR')
  IRR,
  @JsonValue('CURRENCY_ISK')
  ISK,
  @JsonValue('CURRENCY_JMD')
  JMD,
  @JsonValue('CURRENCY_JOD')
  JOD,
  @JsonValue('CURRENCY_KES')
  KES,
  @JsonValue('CURRENCY_KGS')
  KGS,
  @JsonValue('CURRENCY_KHR')
  KHR,
  @JsonValue('CURRENCY_KMF')
  KMF,
  @JsonValue('CURRENCY_KPW')
  KPW,
  @JsonValue('CURRENCY_KWD')
  KWD,
  @JsonValue('CURRENCY_KYD')
  KYD,
  @JsonValue('CURRENCY_KZT')
  KZT,
  @JsonValue('CURRENCY_LAK')
  LAK,
  @JsonValue('CURRENCY_LBP')
  LBP,
  @JsonValue('CURRENCY_LKR')
  LKR,
  @JsonValue('CURRENCY_LRD')
  LRD,
  @JsonValue('CURRENCY_LSL')
  LSL,
  @JsonValue('CURRENCY_LYD')
  LYD,
  @JsonValue('CURRENCY_MAD')
  MAD,
  @JsonValue('CURRENCY_MDL')
  MDL,
  @JsonValue('CURRENCY_MGA')
  MGA,
  @JsonValue('CURRENCY_MKD')
  MKD,
  @JsonValue('CURRENCY_MMK')
  MMK,
  @JsonValue('CURRENCY_MNT')
  MNT,
  @JsonValue('CURRENCY_MOP')
  MOP,
  @JsonValue('CURRENCY_MRU')
  MRU,
  @JsonValue('CURRENCY_MUR')
  MUR,
  @JsonValue('CURRENCY_MVR')
  MVR,
  @JsonValue('CURRENCY_MWK')
  MWK,
  @JsonValue('CURRENCY_MXN')
  MXN,
  @JsonValue('CURRENCY_MXV')
  MXV,
  @JsonValue('CURRENCY_MZN')
  MZN,
  @JsonValue('CURRENCY_NAD')
  NAD,
  @JsonValue('CURRENCY_NGN')
  NGN,
  @JsonValue('CURRENCY_NIO')
  NIO,
  @JsonValue('CURRENCY_NOK')
  NOK,
  @JsonValue('CURRENCY_NPR')
  NPR,
  @JsonValue('CURRENCY_NZD')
  NZD,
  @JsonValue('CURRENCY_OMR')
  OMR,
  @JsonValue('CURRENCY_PAB')
  PAB,
  @JsonValue('CURRENCY_PEN')
  PEN,
  @JsonValue('CURRENCY_PGK')
  PGK,
  @JsonValue('CURRENCY_PHP')
  PHP,
  @JsonValue('CURRENCY_PKR')
  PKR,
  @JsonValue('CURRENCY_PLN')
  PLN,
  @JsonValue('CURRENCY_PYG')
  PYG,
  @JsonValue('CURRENCY_QAR')
  QAR,
  @JsonValue('CURRENCY_RON')
  RON,
  @JsonValue('CURRENCY_RSD')
  RSD,
  @JsonValue('CURRENCY_RUB')
  RUB,
  @JsonValue('CURRENCY_RWF')
  RWF,
  @JsonValue('CURRENCY_SAR')
  SAR,
  @JsonValue('CURRENCY_SBD')
  SBD,
  @JsonValue('CURRENCY_SCR')
  SCR,
  @JsonValue('CURRENCY_SDG')
  SDG,
  @JsonValue('CURRENCY_SEK')
  SEK,
  @JsonValue('CURRENCY_SHP')
  SHP,
  @JsonValue('CURRENCY_SLE')
  SLE,
  @JsonValue('CURRENCY_SLL')
  SLL,
  @JsonValue('CURRENCY_SOS')
  SOS,
  @JsonValue('CURRENCY_SRD')
  SRD,
  @JsonValue('CURRENCY_SSP')
  SSP,
  @JsonValue('CURRENCY_STN')
  STN,
  @JsonValue('CURRENCY_SVC')
  SVC,
  @JsonValue('CURRENCY_SYP')
  SYP,
  @JsonValue('CURRENCY_SZL')
  SZL,
  @JsonValue('CURRENCY_TJS')
  TJS,
  @JsonValue('CURRENCY_TMT')
  TMT,
  @JsonValue('CURRENCY_TND')
  TND,
  @JsonValue('CURRENCY_TOP')
  TOP,
  @JsonValue('CURRENCY_TRY')
  TRY,
  @JsonValue('CURRENCY_TTD')
  TTD,
  @JsonValue('CURRENCY_TWD')
  TWD,
  @JsonValue('CURRENCY_TZS')
  TZS,
  @JsonValue('CURRENCY_UAH')
  UAH,
  @JsonValue('CURRENCY_UGX')
  UGX,
  @JsonValue('CURRENCY_USN')
  USN,
  @JsonValue('CURRENCY_UYI')
  UYI,
  @JsonValue('CURRENCY_UYU')
  UYU,
  @JsonValue('CURRENCY_UYW')
  UYW,
  @JsonValue('CURRENCY_UZS')
  UZS,
  @JsonValue('CURRENCY_VED')
  VED,
  @JsonValue('CURRENCY_VES')
  VES,
  @JsonValue('CURRENCY_VUV')
  VUV,
  @JsonValue('CURRENCY_WST')
  WST,
  @JsonValue('CURRENCY_XAF')
  XAF,
  @JsonValue('CURRENCY_XAG')
  XAG,
  @JsonValue('CURRENCY_XAU')
  XAU,
  @JsonValue('CURRENCY_XBA')
  XBA,
  @JsonValue('CURRENCY_XBB')
  XBB,
  @JsonValue('CURRENCY_XBC')
  XBC,
  @JsonValue('CURRENCY_XBD')
  XBD,
  @JsonValue('CURRENCY_XCD')
  XCD,
  @JsonValue('CURRENCY_XDR')
  XDR,
  @JsonValue('CURRENCY_XOF')
  XOF,
  @JsonValue('CURRENCY_XPD')
  XPD,
  @JsonValue('CURRENCY_XPF')
  XPF,
  @JsonValue('CURRENCY_XPT')
  XPT,
  @JsonValue('CURRENCY_XSU')
  XSU,
  @JsonValue('CURRENCY_XTS')
  XTS,
  @JsonValue('CURRENCY_XUA')
  XUA,
  @JsonValue('CURRENCY_XXX')
  XXX,
  @JsonValue('CURRENCY_YER')
  YER,
  @JsonValue('CURRENCY_ZAR')
  ZAR,
  @JsonValue('CURRENCY_ZMW')
  ZMW,
  @JsonValue('CURRENCY_ZWL')
  ZWL,
}
